INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (1, 'The Shawshank Redemption', TO_DATE('1994-10-14', 'YYYY-MM-DD'), 'Drama', 'Frank Darabont');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (2, 'The Godfather', TO_DATE('1972-03-24', 'YYYY-MM-DD'), 'Crime', 'Francis Ford Coppola');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (3, 'The Dark Knight', TO_DATE('2008-07-18', 'YYYY-MM-DD'), 'Action', 'Christopher Nolan');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (4, 'Pulp Fiction', TO_DATE('1994-10-14', 'YYYY-MM-DD'), 'Crime', 'Quentin Tarantino');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (5, 'Forrest Gump', TO_DATE('1994-07-06', 'YYYY-MM-DD'), 'Drama', 'Robert Zemeckis');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (6, 'Inception', TO_DATE('2010-07-16', 'YYYY-MM-DD'), 'Sci-Fi', 'Christopher Nolan');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (7, 'Fight Club', TO_DATE('1999-10-15', 'YYYY-MM-DD'), 'Drama', 'David Fincher');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (8, 'The Matrix', TO_DATE('1999-03-31', 'YYYY-MM-DD'), 'Sci-Fi', 'The Wachowskis');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (9, 'Goodfellas', TO_DATE('1990-09-19', 'YYYY-MM-DD'), 'Crime', 'Martin Scorsese');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (10, 'The Silence of the Lambs', TO_DATE('1991-02-14', 'YYYY-MM-DD'), 'Thriller', 'Jonathan Demme');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (11, 'Schindler''s List', TO_DATE('1993-12-15', 'YYYY-MM-DD'), 'Drama', 'Steven Spielberg');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (12, 'Interstellar', TO_DATE('2014-11-07', 'YYYY-MM-DD'), 'Sci-Fi', 'Christopher Nolan');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (13, 'Gladiator', TO_DATE('2000-05-05', 'YYYY-MM-DD'), 'Action', 'Ridley Scott');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (14, 'The Prestige', TO_DATE('2006-10-20', 'YYYY-MM-DD'), 'Drama', 'Christopher Nolan');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (15, 'The Departed', TO_DATE('2006-10-06', 'YYYY-MM-DD'), 'Crime', 'Martin Scorsese');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (16, 'The Lord of the Rings: The Return of the King', TO_DATE('2003-12-17', 'YYYY-MM-DD'), 'Fantasy', 'Peter Jackson');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (17, 'The Lion King', TO_DATE('1994-06-24', 'YYYY-MM-DD'), 'Animation', 'Roger Allers, Rob Minkoff');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (18, 'The Empire Strikes Back', TO_DATE('1980-05-21', 'YYYY-MM-DD'), 'Sci-Fi', 'Irvin Kershner');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (19, 'Back to the Future', TO_DATE('1985-07-03', 'YYYY-MM-DD'), 'Sci-Fi', 'Robert Zemeckis');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (20, 'Terminator 2: Judgment Day', TO_DATE('1991-07-03', 'YYYY-MM-DD'), 'Action', 'James Cameron');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (21, 'Saving Private Ryan', TO_DATE('1998-07-24', 'YYYY-MM-DD'), 'War', 'Steven Spielberg');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (22, 'The Green Mile', TO_DATE('1999-12-10', 'YYYY-MM-DD'), 'Drama', 'Frank Darabont');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (23, 'The Godfather: Part II', TO_DATE('1974-12-20', 'YYYY-MM-DD'), 'Crime', 'Francis Ford Coppola');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (24, 'Alien', TO_DATE('1979-05-25', 'YYYY-MM-DD'), 'Sci-Fi', 'Ridley Scott');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (25, 'Raiders of the Lost Ark', TO_DATE('1981-06-12', 'YYYY-MM-DD'), 'Adventure', 'Steven Spielberg');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (26, 'The Shining', TO_DATE('1980-05-23', 'YYYY-MM-DD'), 'Horror', 'Stanley Kubrick');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (27, 'Braveheart', TO_DATE('1995-05-24', 'YYYY-MM-DD'), 'History', 'Mel Gibson');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (28, 'Titanic', TO_DATE('1997-12-19', 'YYYY-MM-DD'), 'Romance', 'James Cameron');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (29, 'Avatar', TO_DATE('2009-12-18', 'YYYY-MM-DD'), 'Sci-Fi', 'James Cameron');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (30, 'The Avengers', TO_DATE('2012-05-04', 'YYYY-MM-DD'), 'Action', 'Joss Whedon');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (31, 'Star Wars', TO_DATE('1977-05-25', 'YYYY-MM-DD'), 'Sci-Fi', 'George Lucas');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (32, 'Jurassic Park', TO_DATE('1993-06-11', 'YYYY-MM-DD'), 'Sci-Fi', 'Steven Spielberg');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (33, 'The Matrix Reloaded', TO_DATE('2003-05-15', 'YYYY-MM-DD'), 'Sci-Fi', 'The Wachowskis');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (34, 'Inglourious Basterds', TO_DATE('2009-08-21', 'YYYY-MM-DD'), 'War', 'Quentin Tarantino');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (35, 'The Usual Suspects', TO_DATE('1995-08-16', 'YYYY-MM-DD'), 'Crime', 'Bryan Singer');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (36, 'American Beauty', TO_DATE('1999-10-01', 'YYYY-MM-DD'), 'Drama', 'Sam Mendes');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (37, 'A Clockwork Orange', TO_DATE('1971-12-19', 'YYYY-MM-DD'), 'Drama', 'Stanley Kubrick');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (38, 'Memento', TO_DATE('2000-10-11', 'YYYY-MM-DD'), 'Thriller', 'Christopher Nolan');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (39, 'Gladiator', TO_DATE('2000-05-05', 'YYYY-MM-DD'), 'Action', 'Ridley Scott');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (40, 'Se7en', TO_DATE('1995-09-22', 'YYYY-MM-DD'), 'Thriller', 'David Fincher');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (41, 'Apocalypse Now', TO_DATE('1979-08-15', 'YYYY-MM-DD'), 'War', 'Francis Ford Coppola');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (42, 'The Pianist', TO_DATE('2002-09-25', 'YYYY-MM-DD'), 'Drama', 'Roman Polanski');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (43, 'Django Unchained', TO_DATE('2012-12-25', 'YYYY-MM-DD'), 'Western', 'Quentin Tarantino');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (44, 'The Wolf of Wall Street', TO_DATE('2013-12-25', 'YYYY-MM-DD'), 'Biography', 'Martin Scorsese');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (45, 'Casino', TO_DATE('1995-11-22', 'YYYY-MM-DD'), 'Crime', 'Martin Scorsese');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (46, 'Mad Max: Fury Road', TO_DATE('2015-05-15', 'YYYY-MM-DD'), 'Action', 'George Miller');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (47, 'The Departed', TO_DATE('2006-10-06', 'YYYY-MM-DD'), 'Crime', 'Martin Scorsese');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (48, 'The Grand Budapest Hotel', TO_DATE('2014-03-28', 'YYYY-MM-DD'), 'Comedy', 'Wes Anderson');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (49, 'The Dark Knight Rises', TO_DATE('2012-07-20', 'YYYY-MM-DD'), 'Action', 'Christopher Nolan');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (50, 'Gone Girl', TO_DATE('2014-10-03', 'YYYY-MM-DD'), 'Thriller', 'David Fincher');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (51, 'The Social Network', TO_DATE('2010-10-01', 'YYYY-MM-DD'), 'Biography', 'David Fincher');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (52, 'The Imitation Game', TO_DATE('2014-12-25', 'YYYY-MM-DD'), 'Biography', 'Morten Tyldum');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (53, 'Whiplash', TO_DATE('2014-10-10', 'YYYY-MM-DD'), 'Drama', 'Damien Chazelle');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (54, 'Birdman', TO_DATE('2014-10-17', 'YYYY-MM-DD'), 'Comedy', 'Alejandro G. Iñárritu');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (55, 'La La Land', TO_DATE('2016-12-09', 'YYYY-MM-DD'), 'Musical', 'Damien Chazelle');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (56, '12 Years a Slave', TO_DATE('2013-11-08', 'YYYY-MM-DD'), 'Biography', 'Steve McQueen');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (57, 'Moonlight', TO_DATE('2016-10-21', 'YYYY-MM-DD'), 'Drama', 'Barry Jenkins');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (58, 'Spotlight', TO_DATE('2015-11-06', 'YYYY-MM-DD'), 'Biography', 'Tom McCarthy');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (59, 'Parasite', TO_DATE('2019-05-30', 'YYYY-MM-DD'), 'Drama', 'Bong Joon-ho');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (60, 'Joker', TO_DATE('2019-10-04', 'YYYY-MM-DD'), 'Crime', 'Todd Phillips');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (61, '1917', TO_DATE('2019-12-25', 'YYYY-MM-DD'), 'War', 'Sam Mendes');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (62, 'Jojo Rabbit', TO_DATE('2019-10-18', 'YYYY-MM-DD'), 'Comedy', 'Taika Waititi');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (63, 'Blade Runner 2049', TO_DATE('2017-10-06', 'YYYY-MM-DD'), 'Sci-Fi', 'Denis Villeneuve');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (64, 'Dunkirk', TO_DATE('2017-07-21', 'YYYY-MM-DD'), 'War', 'Christopher Nolan');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (65, 'Black Panther', TO_DATE('2018-02-16', 'YYYY-MM-DD'), 'Action', 'Ryan Coogler');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (66, 'The Irishman', TO_DATE('2019-11-01', 'YYYY-MM-DD'), 'Crime', 'Martin Scorsese');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (67, 'Ford v Ferrari', TO_DATE('2019-11-15', 'YYYY-MM-DD'), 'Action', 'James Mangold');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (68, 'Once Upon a Time in Hollywood', TO_DATE('2019-07-26', 'YYYY-MM-DD'), 'Comedy', 'Quentin Tarantino');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (69, 'A Star Is Born', TO_DATE('2018-10-05', 'YYYY-MM-DD'), 'Drama', 'Bradley Cooper');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (70, 'The Shape of Water', TO_DATE('2017-12-22', 'YYYY-MM-DD'), 'Fantasy', 'Guillermo del Toro');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (71, 'Logan', TO_DATE('2017-03-03', 'YYYY-MM-DD'), 'Action', 'James Mangold');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (72, 'Spider-Man: Into the Spider-Verse', TO_DATE('2018-12-14', 'YYYY-MM-DD'), 'Animation', 'Peter Ramsey, Rodney Rothman, Bob Persichetti');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (73, 'Bohemian Rhapsody', TO_DATE('2018-11-02', 'YYYY-MM-DD'), 'Biography', 'Bryan Singer');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (74, 'The Revenant', TO_DATE('2015-12-25', 'YYYY-MM-DD'), 'Adventure', 'Alejandro G. Iñárritu');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (75, 'Gravity', TO_DATE('2013-10-04', 'YYYY-MM-DD'), 'Sci-Fi', 'Alfonso Cuarón');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (76, 'The Martian', TO_DATE('2015-10-02', 'YYYY-MM-DD'), 'Sci-Fi', 'Ridley Scott');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (77, 'Deadpool', TO_DATE('2016-02-12', 'YYYY-MM-DD'), 'Action', 'Tim Miller');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (78, 'Doctor Strange', TO_DATE('2016-11-04', 'YYYY-MM-DD'), 'Fantasy', 'Scott Derrickson');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (79, 'Guardians of the Galaxy', TO_DATE('2014-08-01', 'YYYY-MM-DD'), 'Sci-Fi', 'James Gunn');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (80, 'Wonder Woman', TO_DATE('2017-06-02', 'YYYY-MM-DD'), 'Action', 'Patty Jenkins');

-- livesql.oracle.com allow to insert part of whole inserts, divide inserts into parts

INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (81, 'Shutter Island', TO_DATE('2010-02-19', 'YYYY-MM-DD'), 'Thriller', 'Martin Scorsese');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (82, 'Kingsman: The Secret Service', TO_DATE('2015-02-13', 'YYYY-MM-DD'), 'Action', 'Matthew Vaughn');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (83, 'John Wick', TO_DATE('2014-10-24', 'YYYY-MM-DD'), 'Action', 'Chad Stahelski');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (84, 'Skyfall', TO_DATE('2012-11-09', 'YYYY-MM-DD'), 'Action', 'Sam Mendes');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (85, 'Blade Runner', TO_DATE('1982-06-25', 'YYYY-MM-DD'), 'Sci-Fi', 'Ridley Scott');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (86, 'The Big Short', TO_DATE('2015-12-11', 'YYYY-MM-DD'), 'Biography', 'Adam McKay');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (87, 'Mad Max', TO_DATE('1979-04-12', 'YYYY-MM-DD'), 'Action', 'George Miller');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (88, 'Rocky', TO_DATE('1976-11-21', 'YYYY-MM-DD'), 'Drama', 'John G. Avildsen');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (89, 'The Exorcist', TO_DATE('1973-12-26', 'YYYY-MM-DD'), 'Horror', 'William Friedkin');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (90, 'Jaws', TO_DATE('1975-06-20', 'YYYY-MM-DD'), 'Thriller', 'Steven Spielberg');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (91, 'E.T. the Extra-Terrestrial', TO_DATE('1982-06-11', 'YYYY-MM-DD'), 'Sci-Fi', 'Steven Spielberg');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (92, 'The Terminator', TO_DATE('1984-10-26', 'YYYY-MM-DD'), 'Action', 'James Cameron');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (93, 'Indiana Jones and the Last Crusade', TO_DATE('1989-05-24', 'YYYY-MM-DD'), 'Adventure', 'Steven Spielberg');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (94, 'Jurassic World', TO_DATE('2015-06-12', 'YYYY-MM-DD'), 'Sci-Fi', 'Colin Trevorrow');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (95, 'The Sixth Sense', TO_DATE('1999-08-06', 'YYYY-MM-DD'), 'Thriller', 'M. Night Shyamalan');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (96, 'Frozen', TO_DATE('2013-11-27', 'YYYY-MM-DD'), 'Animation', 'Chris Buck, Jennifer Lee');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (97, 'The Incredibles', TO_DATE('2004-11-05', 'YYYY-MM-DD'), 'Animation', 'Brad Bird');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (98, 'Finding Nemo', TO_DATE('2003-05-30', 'YYYY-MM-DD'), 'Animation', 'Andrew Stanton, Lee Unkrich');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (99, 'Toy Story', TO_DATE('1995-11-22', 'YYYY-MM-DD'), 'Animation', 'John Lasseter');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (100, 'Toy Story 3', TO_DATE('2010-06-18', 'YYYY-MM-DD'), 'Animation', 'Lee Unkrich');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (101, 'Up', TO_DATE('2009-05-29', 'YYYY-MM-DD'), 'Animation', 'Pete Docter, Bob Peterson');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (102, 'Monsters, Inc.', TO_DATE('2001-11-02', 'YYYY-MM-DD'), 'Animation', 'Pete Docter, David Silverman, Lee Unkrich');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (103, 'Inside Out', TO_DATE('2015-06-19', 'YYYY-MM-DD'), 'Animation', 'Pete Docter, Ronnie del Carmen');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (104, 'The Lion King (2019)', TO_DATE('2019-07-19', 'YYYY-MM-DD'), 'Animation', 'Jon Favreau');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (105, 'Coco', TO_DATE('2017-11-22', 'YYYY-MM-DD'), 'Animation', 'Lee Unkrich, Adrian Molina');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (106, 'Ratatouille', TO_DATE('2007-06-29', 'YYYY-MM-DD'), 'Animation', 'Brad Bird, Jan Pinkava');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (107, 'WALL-E', TO_DATE('2008-06-27', 'YYYY-MM-DD'), 'Animation', 'Andrew Stanton');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (108, 'Brave', TO_DATE('2012-06-22', 'YYYY-MM-DD'), 'Animation', 'Mark Andrews, Brenda Chapman, Steve Purcell');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (109, 'Finding Dory', TO_DATE('2016-06-17', 'YYYY-MM-DD'), 'Animation', 'Andrew Stanton, Angus MacLane');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (110, 'Zootopia', TO_DATE('2016-03-04', 'YYYY-MM-DD'), 'Animation', 'Byron Howard, Rich Moore, Jared Bush');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (111, 'Tangled', TO_DATE('2010-11-24', 'YYYY-MM-DD'), 'Animation', 'Nathan Greno, Byron Howard');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (112, 'Moana', TO_DATE('2016-11-23', 'YYYY-MM-DD'), 'Animation', 'Ron Clements, John Musker');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (113, 'Aladdin (2019)', TO_DATE('2019-05-24', 'YYYY-MM-DD'), 'Fantasy', 'Guy Ritchie');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (114, 'Beauty and the Beast (2017)', TO_DATE('2017-03-17', 'YYYY-MM-DD'), 'Fantasy', 'Bill Condon');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (115, 'Maleficent', TO_DATE('2014-05-30', 'YYYY-MM-DD'), 'Fantasy', 'Robert Stromberg');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (116, 'Cinderella (2015)', TO_DATE('2015-03-13', 'YYYY-MM-DD'), 'Fantasy', 'Kenneth Branagh');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (117, 'Frozen II', TO_DATE('2019-11-22', 'YYYY-MM-DD'), 'Animation', 'Chris Buck, Jennifer Lee');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (118, 'The Incredibles 2', TO_DATE('2018-06-15', 'YYYY-MM-DD'), 'Animation', 'Brad Bird');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (119, 'Toy Story 4', TO_DATE('2019-06-21', 'YYYY-MM-DD'), 'Animation', 'Josh Cooley');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (120, 'The Lion King', TO_DATE('1994-06-24', 'YYYY-MM-DD'), 'Animation', 'Roger Allers, Rob Minkoff');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (121, 'Aladdin (1992)', TO_DATE('1992-11-25', 'YYYY-MM-DD'), 'Animation', 'Ron Clements, John Musker');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (122, 'Beauty and the Beast (1991)', TO_DATE('1991-11-22', 'YYYY-MM-DD'), 'Animation', 'Gary Trousdale, Kirk Wise');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (123, 'The Little Mermaid', TO_DATE('1989-11-17', 'YYYY-MM-DD'), 'Animation', 'Ron Clements, John Musker');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (124, 'Mulan (1998)', TO_DATE('1998-06-19', 'YYYY-MM-DD'), 'Animation', 'Barry Cook, Tony Bancroft');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (125, 'Sleeping Beauty', TO_DATE('1959-01-29', 'YYYY-MM-DD'), 'Animation', 'Clyde Geronimi');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (126, 'Snow White and the Seven Dwarfs', TO_DATE('1937-12-21', 'YYYY-MM-DD'), 'Animation', 'William Cottrell, David Hand, Wilfred Jackson, Larry Morey, Perce Pearce, Ben Sharpsteen');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (127, 'Pinocchio', TO_DATE('1940-02-23', 'YYYY-MM-DD'), 'Animation', 'Norman Ferguson, T. Hee, Wilfred Jackson, Jack Kinney, Hamilton Luske, Bill Roberts, Ben Sharpsteen');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (128, 'Bambi', TO_DATE('1942-08-21', 'YYYY-MM-DD'), 'Animation', 'David Hand');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (129, 'Alice in Wonderland (1951)', TO_DATE('1951-07-28', 'YYYY-MM-DD'), 'Animation', 'Clyde Geronimi, Wilfred Jackson, Hamilton Luske');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (130, 'Peter Pan (1953)', TO_DATE('1953-02-05', 'YYYY-MM-DD'), 'Animation', 'Clyde Geronimi, Wilfred Jackson, Hamilton Luske');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (131, 'Lady and the Tramp', TO_DATE('1955-06-22', 'YYYY-MM-DD'), 'Animation', 'Clyde Geronimi, Wilfred Jackson, Hamilton Luske');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (132, 'One Hundred and One Dalmatians', TO_DATE('1961-01-25', 'YYYY-MM-DD'), 'Animation', 'Clyde Geronimi, Hamilton Luske, Wolfgang Reitherman');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (133, 'The Sword in the Stone', TO_DATE('1963-12-25', 'YYYY-MM-DD'), 'Animation', 'Wolfgang Reitherman');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (134, 'The Jungle Book (1967)', TO_DATE('1967-10-18', 'YYYY-MM-DD'), 'Animation', 'Wolfgang Reitherman');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (135, 'The Aristocats', TO_DATE('1970-12-11', 'YYYY-MM-DD'), 'Animation', 'Wolfgang Reitherman');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (136, 'Robin Hood', TO_DATE('1973-11-08', 'YYYY-MM-DD'), 'Animation', 'Wolfgang Reitherman');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (137, 'The Rescuers', TO_DATE('1977-06-22', 'YYYY-MM-DD'), 'Animation', 'John Lounsbery, Wolfgang Reitherman, Art Stevens');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (138, 'The Fox and the Hound', TO_DATE('1981-07-10', 'YYYY-MM-DD'), 'Animation', 'Ted Berman, Richard Rich, Art Stevens');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (139, 'The Black Cauldron', TO_DATE('1985-07-24', 'YYYY-MM-DD'), 'Animation', 'Ted Berman, Richard Rich');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (140, 'The Great Mouse Detective', TO_DATE('1986-07-02', 'YYYY-MM-DD'), 'Animation', 'Ron Clements, Burny Mattinson, David Michener, John Musker');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (141, 'Oliver & Company', TO_DATE('1988-11-18', 'YYYY-MM-DD'), 'Animation', 'George Scribner');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (142, 'The Little Mermaid', TO_DATE('1989-11-17', 'YYYY-MM-DD'), 'Animation', 'Ron Clements, John Musker');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (143, 'The Rescuers Down Under', TO_DATE('1990-11-16', 'YYYY-MM-DD'), 'Animation', 'Hendel Butoy, Mike Gabriel');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (144, 'Beauty and the Beast (1991)', TO_DATE('1991-11-22', 'YYYY-MM-DD'), 'Animation', 'Gary Trousdale, Kirk Wise');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (145, 'Aladdin (1992)', TO_DATE('1992-11-25', 'YYYY-MM-DD'), 'Animation', 'Ron Clements, John Musker');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (146, 'The Lion King', TO_DATE('1994-06-24', 'YYYY-MM-DD'), 'Animation', 'Roger Allers, Rob Minkoff');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (147, 'Pocahontas', TO_DATE('1995-06-23', 'YYYY-MM-DD'), 'Animation', 'Mike Gabriel, Eric Goldberg');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (148, 'The Hunchback of Notre Dame', TO_DATE('1996-06-21', 'YYYY-MM-DD'), 'Animation', 'Gary Trousdale, Kirk Wise');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (149, 'Hercules', TO_DATE('1997-06-27', 'YYYY-MM-DD'), 'Animation', 'Ron Clements, John Musker');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (150, 'Mulan', TO_DATE('1998-06-19', 'YYYY-MM-DD'), 'Animation', 'Barry Cook, Tony Bancroft');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (151, 'Tarzan', TO_DATE('1999-06-18', 'YYYY-MM-DD'), 'Animation', 'Chris Buck, Kevin Lima');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (152, 'Dinosaur', TO_DATE('2000-05-19', 'YYYY-MM-DD'), 'Animation', 'Eric Leighton, Ralph Zondag');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (153, 'The Emperors New Groove', TO_DATE('2000-12-15', 'YYYY-MM-DD'), 'Animation', 'Mark Dindal');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (154, 'Atlantis: The Lost Empire', TO_DATE('2001-06-15', 'YYYY-MM-DD'), 'Animation', 'Gary Trousdale, Kirk Wise');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (155, 'Lilo & Stitch', TO_DATE('2002-06-21', 'YYYY-MM-DD'), 'Animation', 'Dean DeBlois, Chris Sanders');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (156, 'Treasure Planet', TO_DATE('2002-11-27', 'YYYY-MM-DD'), 'Animation', 'Ron Clements, John Musker');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (157, 'Brother Bear', TO_DATE('2003-11-01', 'YYYY-MM-DD'), 'Animation', 'Aaron Blaise, Robert Walker');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (158, 'Home on the Range', TO_DATE('2004-04-02', 'YYYY-MM-DD'), 'Animation', 'Will Finn, John Sanford');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (159, 'Chicken Little', TO_DATE('2005-11-04', 'YYYY-MM-DD'), 'Animation', 'Mark Dindal');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (160, 'Meet the Robinsons', TO_DATE('2007-03-30', 'YYYY-MM-DD'), 'Animation', 'Stephen J. Anderson');

-- livesql.oracle.com allow to insert part of whole inserts, divide inserts into parts


INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (161, 'Bolt', TO_DATE('2008-11-21', 'YYYY-MM-DD'), 'Animation', 'Byron Howard, Chris Williams');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (162, 'The Princess and the Frog', TO_DATE('2009-12-11', 'YYYY-MM-DD'), 'Animation', 'Ron Clements, John Musker');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (163, 'Tangled', TO_DATE('2010-11-24', 'YYYY-MM-DD'), 'Animation', 'Nathan Greno, Byron Howard');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (164, 'Winnie the Pooh', TO_DATE('2011-07-15', 'YYYY-MM-DD'), 'Animation', 'Stephen J. Anderson, Don Hall');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (165, 'Wreck-It Ralph', TO_DATE('2012-11-02', 'YYYY-MM-DD'), 'Animation', 'Rich Moore');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (166, 'Frozen', TO_DATE('2013-11-27', 'YYYY-MM-DD'), 'Animation', 'Chris Buck, Jennifer Lee');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (167, 'Big Hero 6', TO_DATE('2014-11-07', 'YYYY-MM-DD'), 'Animation', 'Don Hall, Chris Williams');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (168, 'Zootopia', TO_DATE('2016-03-04', 'YYYY-MM-DD'), 'Animation', 'Byron Howard, Rich Moore, Jared Bush');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (169, 'Moana', TO_DATE('2016-11-23', 'YYYY-MM-DD'), 'Animation', 'Ron Clements, John Musker');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (170, 'Ralph Breaks the Internet', TO_DATE('2018-11-21', 'YYYY-MM-DD'), 'Animation', 'Rich Moore, Phil Johnston');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (171, 'Frozen II', TO_DATE('2019-11-22', 'YYYY-MM-DD'), 'Animation', 'Chris Buck, Jennifer Lee');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (172, 'Encanto', TO_DATE('2021-11-24', 'YYYY-MM-DD'), 'Animation', 'Jared Bush, Byron Howard, Charise Castro Smith');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (173, 'Raya and the Last Dragon', TO_DATE('2021-03-05', 'YYYY-MM-DD'), 'Animation', 'Don Hall, Carlos López Estrada');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (174, 'Lightyear', TO_DATE('2022-06-17', 'YYYY-MM-DD'), 'Animation', 'Angus MacLane');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (175, 'Turning Red', TO_DATE('2022-03-11', 'YYYY-MM-DD'), 'Animation', 'Domee Shi');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (176, 'Luca', TO_DATE('2021-06-18', 'YYYY-MM-DD'), 'Animation', 'Enrico Casarosa');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (177, 'Soul', TO_DATE('2020-12-25', 'YYYY-MM-DD'), 'Animation', 'Pete Docter, Kemp Powers');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (178, 'Onward', TO_DATE('2020-03-06', 'YYYY-MM-DD'), 'Animation', 'Dan Scanlon');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (179, 'Frozen', TO_DATE('2013-11-27', 'YYYY-MM-DD'), 'Animation', 'Chris Buck, Jennifer Lee');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (180, 'WALL-E', TO_DATE('2008-06-27', 'YYYY-MM-DD'), 'Animation', 'Andrew Stanton');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (181, 'Coco', TO_DATE('2017-11-22', 'YYYY-MM-DD'), 'Animation', 'Lee Unkrich, Adrian Molina');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (182, 'Ratatouille', TO_DATE('2007-06-29', 'YYYY-MM-DD'), 'Animation', 'Brad Bird, Jan Pinkava');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (183, 'Finding Nemo', TO_DATE('2003-05-30', 'YYYY-MM-DD'), 'Animation', 'Andrew Stanton, Lee Unkrich');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (184, 'Monsters, Inc.', TO_DATE('2001-11-02', 'YYYY-MM-DD'), 'Animation', 'Pete Docter, David Silverman, Lee Unkrich');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (185, 'The Incredibles', TO_DATE('2004-11-05', 'YYYY-MM-DD'), 'Animation', 'Brad Bird');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (186, 'Up', TO_DATE('2009-05-29', 'YYYY-MM-DD'), 'Animation', 'Pete Docter, Bob Peterson');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (187, 'Toy Story', TO_DATE('1995-11-22', 'YYYY-MM-DD'), 'Animation', 'John Lasseter');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (188, 'Toy Story 2', TO_DATE('1999-11-24', 'YYYY-MM-DD'), 'Animation', 'John Lasseter, Ash Brannon, Lee Unkrich');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (189, 'Toy Story 3', TO_DATE('2010-06-18', 'YYYY-MM-DD'), 'Animation', 'Lee Unkrich');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (190, 'Toy Story 4', TO_DATE('2019-06-21', 'YYYY-MM-DD'), 'Animation', 'Josh Cooley');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (191, 'Cars', TO_DATE('2006-06-09', 'YYYY-MM-DD'), 'Animation', 'John Lasseter, Joe Ranft');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (192, 'Cars 2', TO_DATE('2011-06-24', 'YYYY-MM-DD'), 'Animation', 'John Lasseter, Brad Lewis');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (193, 'Cars 3', TO_DATE('2017-06-16', 'YYYY-MM-DD'), 'Animation', 'Brian Fee');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (194, 'Finding Dory', TO_DATE('2016-06-17', 'YYYY-MM-DD'), 'Animation', 'Andrew Stanton, Angus MacLane');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (195, 'Monsters University', TO_DATE('2013-06-21', 'YYYY-MM-DD'), 'Animation', 'Dan Scanlon');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (196, 'The Good Dinosaur', TO_DATE('2015-11-25', 'YYYY-MM-DD'), 'Animation', 'Peter Sohn');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (197, 'Brave', TO_DATE('2012-06-22', 'YYYY-MM-DD'), 'Animation', 'Mark Andrews, Brenda Chapman');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (198, 'Inside Out', TO_DATE('2015-06-19', 'YYYY-MM-DD'), 'Animation', 'Pete Docter');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (199, 'Soul', TO_DATE('2020-12-25', 'YYYY-MM-DD'), 'Animation', 'Pete Docter, Kemp Powers');
INSERT INTO Movies (movie_id, title, release_date, genre, director) VALUES (200, 'Turning Red', TO_DATE('2022-03-11', 'YYYY-MM-DD'), 'Animation', 'Domee Shi');


-- INSERT TO CINEMA

INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (1, 'Cinema City', 'Warsaw', 250);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (2, 'Multikino', 'Krakow', 300);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (3, 'Helios', 'Wroclaw', 200);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (4, 'Cinema Park', 'Poznan', 220);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (5, 'Silver Screen', 'Gdansk', 180);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (6, 'IMAX', 'Katowice', 350);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (7, 'Kino Luna', 'Warsaw', 150);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (8, 'Kino Pod Baranami', 'Krakow', 120);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (9, 'Kino Muza', 'Poznan', 100);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (10, 'Kino Pionier', 'Szczecin', 90);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (11, 'Kino Atlantic', 'Warsaw', 130);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (12, 'Kino Nowe Horyzonty', 'Wroclaw', 280);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (13, 'Kino Amok', 'Gliwice', 110);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (14, 'Kino Rialto', 'Katowice', 140);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (15, 'Kino Charlie', 'Lodz', 160);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (16, 'Kino Millennium', 'Rzeszow', 170);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (17, 'Kino Kosmos', 'Szczecin', 210);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (18, 'Kino Zamek', 'Poznan', 100);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (19, 'Kino Bajka', 'Warsaw', 130);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (20, 'Kino Wisla', 'Warsaw', 190);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (21, 'Kino Forum', 'Bialystok', 150);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (22, 'Kino Muranow', 'Warsaw', 200);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (23, 'Kino Iluzjon', 'Warsaw', 230);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (24, 'Kino Rejs', 'Warsaw', 90);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (25, 'Kino Femina', 'Warsaw', 180);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (26, 'Kino Polonia', 'Warsaw', 170);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (27, 'Kino Klaps', 'Krakow', 100);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (28, 'Kino Apollo', 'Poznan', 160);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (29, 'Kino Falenica', 'Warsaw', 120);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (30, 'Kino Teatr', 'Gdynia', 140);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (31, 'Kino Janosik', 'Zakopane', 130);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (32, 'Kino Mazowsze', 'Pruszkow', 150);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (33, 'Kino Odra', 'Wroclaw', 190);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (34, 'Kino Urania', 'Olsztyn', 110);
INSERT INTO Cinema (cinema_id, name, location, capacity) VALUES (35, 'Kino Morskie Oko', 'Sopot', 100);


-- testowy insert jak powinien wyglądać do generowania danych do tabeli screening
INSERT INTO Screenings (screening_id, movie_id, screening_date, cinema_id) VALUES (3, 1, TO_DATE('2015-11-25', 'YYYY-MM-DD'), 35);
INSERT INTO Screenings (screening_id, movie_id, screening_date, cinema_id) VALUES (screening_seq.nextval, 1, TO_DATE('2015-11-25', 'YYYY-MM-DD'), 35);

INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (1, TO_DATE('01-01-2000 9:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (2, TO_DATE('01-01-2000 10:30:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (3, TO_DATE('01-01-2000 11:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (4, TO_DATE('01-01-2000 12:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (5, TO_DATE('01-01-2000 12:30:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (6, TO_DATE('01-01-2000 13:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (7, TO_DATE('01-01-2000 14:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (8, TO_DATE('01-01-2000 15:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (9, TO_DATE('01-01-2000 16:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (10, TO_DATE('01-01-2000 17:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (11, TO_DATE('01-01-2000 18:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (12, TO_DATE('01-01-2000 19:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (13, TO_DATE('01-01-2000 19:30:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (14, TO_DATE('01-01-2000 20:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (15, TO_DATE('01-01-2000 21:00:00', 'DD-MM-YYYY HH24:MI:SS'));
INSERT INTO screenings_timeline (timeline_id, start_time_line) VALUES (16, TO_DATE('01-01-2000 22:00:00', 'DD-MM-YYYY HH24:MI:SS'));